// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbgwevlmahxdljouchsk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBiZ3dldmxtYWh4ZGxqb3VjaHNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc4MTgzODIsImV4cCI6MjA5MzM5NDM4Mn0.y1ICimGrV-5UPV3RdalSgnji94z770VGaTWe_Ar6SfY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});